[tool.briefcase]
project_name = "Hangman"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/hangman"
license = "MIT license"
author = 'coolcoder613'
author_email = "coolcoder613@outlook.com"

[tool.briefcase.app.hangman]
formal_name = "Hangman"
description = "Hangman game"
icon = "src/hangman/resources/hangman"
sources = ['src/hangman']
requires = [
]


[tool.briefcase.app.hangman.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.hangman.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.hangman.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.hangman.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.hangman.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.hangman.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.hangman.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.hangman.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
